import Foundation

/// LaunchAgent plist 的内容定义。
///
/// 这是 RouteBar 的第三个托管产物，和 `sing-box.json`、Surge 的 `[Proxy]` 段地位相同：
/// 全部字段都从 `RouteBarSettings` 派生，设置一变就该重新生成。做成一次性的「创建」按钮
/// 会让同一份信息有两个来源——用户改完路径后 plist 还指着旧的二进制和旧的配置。
public struct LaunchAgentDefinition: Sendable, Equatable {
    public let label: String
    public let programArguments: [String]
    public let standardOutPath: String
    public let standardErrorPath: String

    public nonisolated init(settings: RouteBarSettings) {
        label = settings.launchAgentLabel
        programArguments = [settings.singBoxBinaryPath, "run", "-c", settings.singBoxConfigPath]
        standardOutPath = settings.singBoxLogPath
        standardErrorPath = settings.singBoxErrorLogPath
    }

    /// 写进文件头的标记。
    ///
    /// 用 XML 注释而不是 plist 里的自定义键：launchd 会对不认识的键报警告，而注释在解析前
    /// 就被丢掉，对 launchd 完全透明。同时它又是纯文本，识别时一次子串查找即可，
    /// 不必依赖 settings.json 里另存一个「这是我建的」标志位——那份文件被删就失忆了。
    public nonisolated static let managedMarker = "Generated by RouteBar"

    private nonisolated static let header = """
    <!-- \(managedMarker). 内容由 RouteBar 的「环境」设置派生，手工修改会在下次生成时被覆盖。 -->
    """

    /// 生成 plist 文件内容（含托管标记）。
    public nonisolated func propertyListData() throws -> Data {
        let contents: [String: Any] = [
            "Label": label,
            "ProgramArguments": programArguments,
            "RunAtLoad": true,
            // sing-box 意外退出时由 launchd 拉起来——代理断了要能自愈，
            // 否则用户只会发现「突然上不了网」，而不知道去哪重启。
            "KeepAlive": true,
            "StandardOutPath": standardOutPath,
            "StandardErrorPath": standardErrorPath,
        ]
        let body = try PropertyListSerialization.data(fromPropertyList: contents, format: .xml, options: 0)
        guard let text = String(data: body, encoding: .utf8) else { return body }
        return Data(Self.insertHeader(into: text).utf8)
    }

    /// 把标记注释插到 DOCTYPE 之后、`<plist>` 之前——放在 XML 声明前面会让文件不合法。
    private nonisolated static func insertHeader(into text: String) -> String {
        guard let range = text.range(of: "<plist") else { return text }
        return text.replacingCharacters(in: range.lowerBound..<range.lowerBound, with: header + "\n")
    }

    /// 这份 plist 是不是 RouteBar 写的。
    public nonisolated static func isManaged(_ data: Data) -> Bool {
        String(decoding: data, as: UTF8.self).contains(managedMarker)
    }
}

/// 磁盘上 LaunchAgent 的状态，决定「环境」页给出什么操作。
public enum LaunchAgentState: Sendable, Equatable {
    /// 文件不存在，可以直接创建。
    case missing
    /// RouteBar 写的，且内容与当前设置一致。
    case managedUpToDate
    /// RouteBar 写的，但设置已经变了，需要重新生成。
    case managedOutdated
    /// 别人写的（比如用户手工创建的）。绝不静默覆盖。
    case foreign

    public nonisolated var needsAction: Bool {
        switch self {
        case .managedUpToDate: false
        case .missing, .managedOutdated, .foreign: true
        }
    }

    /// 覆盖前是否必须让用户看过内容并明确确认。
    public nonisolated var requiresConfirmation: Bool { self == .foreign }
}
